[package]
name = "sfn"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
serde = "1.0.144"
serde_derive = "1.0.144"
serde_json = "1.0.85"
